import "./../globals.css";
import { Outfit } from "next/font/google";
import React from "react";
import { Metadata } from "next";
import { twMerge } from "tailwind-merge";

const outfit = Outfit({
	weight: "400",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={outfit.className}>{children}</body>
		</html>
	);
}
