import "../globals.css";
import {Inter, Outfit} from "next/font/google";
import React from "react";
import {Metadata} from "next";
import {sessionHandle} from "@/utils/session";
import {SessionHandler} from "@/app/(admin)/_component/session";
import NavBar from "@/app/(admin)/_component/navbar";
import {twMerge} from "tailwind-merge";
import {Preview} from "@/app/(admin)/_component/mdx/preview";

const inter = Inter({subsets: ["latin"]});

const outfit = Outfit({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
                                           children,
                                         }: {
  children: React.ReactNode;
}) {
  const session = await sessionHandle();
  return (
    <html lang="en">
    <SessionHandler session={session}/>
    <body className={outfit.className}>
    <div className={twMerge("flex relative h-screen overflow-hidden flex-col md:flex-row")}>
      <main className={twMerge("flex flex-col p-4 w-full overflow-y-auto")}>
        {children}
      </main>
    </div>
    </body>
    </html>
  );
}
