import "../globals.css";
import { Outfit } from "next/font/google";
import React from "react";
import { Metadata } from "next";
import { sessionHandle } from "@/utils/session";
import { SessionHandler } from "@/app/(admin)/_component/session";
import { twMerge } from "tailwind-merge";

const outfit = Outfit({
	weight: "400",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = await sessionHandle();
	return (
		<html lang="en">
			<SessionHandler session={session} />
			<body className={outfit.className}>{children}</body>
		</html>
	);
}
